import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    { title: "Dashboard", url: "#" },
    { title: "Conduct History", url: "#" },
    { title: "Notifications", url: "#" },
  ];
  return (
    <div className="flex">
      <SidebarProvider>
        <AppSidebar items={items} />
        <main className="flex-1">{children}</main>
      </SidebarProvider>
    </div>
  );
}
