import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import { LayoutDashboard, History, Bell } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    { title: "Dashboard", url: "/student/dashboard", icon: LayoutDashboard },
    {
      title: "Conduct History",
      url: "/student/conduct-history",
      icon: History,
    },
    { title: "Notifications", url: "/student/notifications", icon: Bell },
  ];
  return (
    <div className="flex h-screen">
      <SidebarProvider>
        <AppSidebar items={items} />
        <main className="flex-1 bg-[#F8F9FA] overflow-y-auto">{children}</main>
      </SidebarProvider>
    </div>
  );
}
